use_frameworks!

platform :ios, '10.0'

target 'StoreHouseRefreshControl_Example' do
  pod 'StoreHouseRefreshControl', :path => '../'

  target 'StoreHouseRefreshControl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
